<a href="https://colab.research.google.com/github/ArjunBhakta/Data-Science-Cohort-20/blob/main/Project_5_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural Language Processing

This project will give you practical experience using Natural Language Processing techniques. This project is in three parts:
- in part 1) you will use a dataset in a CSV file
- in part 2) you will use the Wikipedia API to directly access content
on Wikipedia.
- in part 3) you will make your notebook interactive

#Part 1)

- The CSV file is available at https://ddc-datascience.s3.amazonaws.com/Projects/Project.5-NLP/Data/NLP.csv
- The file contains a list of famous people and a brief overview.
- The goal of part 1) is to ...
  1. Pick one person from the list ( the reference person ) and output 10 other people who's overview are "closest" to the reference person in a Natural Language Processing sense
  1. Also output the sentiment of the overview of the reference person

## Import Packages

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
!pip install textblob -q
from textblob import TextBlob
!pip install umap-learn -q
from sklearn.decomposition import TruncatedSVD
import umap
import plotly.express as px

## Functions

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
from textblob import TextBlob
import pandas as pd


def get_sentiment(text):
    blob = TextBlob(str(text))

    polarity = blob.sentiment.polarity
    subjectivity = blob.sentiment.subjectivity

    if polarity > 0.1:
        sentiment = "Positive"
    elif polarity < -0.1:
        sentiment = "Negative"
    else:
        sentiment = "Neutral"

    return pd.Series({
        "polarity": round(polarity, 3),
        "subjectivity": round(subjectivity, 3),
        "sentiment": sentiment
    })


def find_similar_people(
    reference_person,
    df,
    tfidf_matrix,
    top_n=10,
    include_sentiment=True
):
    """
    Find most similar people using cosine similarity and compare
    against Euclidean distance rankings.
    """

    ref_idx = df[df["name"] == reference_person].index

    if len(ref_idx) == 0:
        print(f"'{reference_person}' not found.")
        return None

    ref_idx = ref_idx[0]

    cosine_scores = cosine_similarity(
        tfidf_matrix[ref_idx],
        tfidf_matrix
    ).flatten()

    euclidean_scores = euclidean_distances(
        tfidf_matrix[ref_idx],
        tfidf_matrix
    ).flatten()

    cosine_ranked = [
        i for i in cosine_scores.argsort()[::-1]
        if i != ref_idx
    ]

    euclidean_ranked = [
        i for i in euclidean_scores.argsort()
        if i != ref_idx
    ]

    top_indices = cosine_ranked[:top_n]

    results = df.iloc[top_indices][["name", "decodedName"]].copy()

    results["cosine_similarity"] = (
        cosine_scores[top_indices].round(4)
    )

    results["euclidean_distance"] = (
        euclidean_scores[top_indices].round(4)
    )

    cosine_rank_lookup = {
        idx: rank + 1
        for rank, idx in enumerate(cosine_ranked)
    }

    euclidean_rank_lookup = {
        idx: rank + 1
        for rank, idx in enumerate(euclidean_ranked)
    }

    results["cosine_rank"] = [
        cosine_rank_lookup[idx]
        for idx in top_indices
    ]

    results["euclidean_rank"] = [
        euclidean_rank_lookup[idx]
        for idx in top_indices
    ]

    results["rank_difference"] = (
        results["cosine_rank"]
        - results["euclidean_rank"]
    ).abs()

    if include_sentiment:
        sentiment_df = (
            df.iloc[top_indices]["text"]
            .apply(get_sentiment)
        )

        results = pd.concat(
            [results, sentiment_df],
            axis=1
        )

    results = results.sort_values(
        "cosine_rank"
    ).reset_index(drop=True)

    results.index += 1

    return results

### Compute umap ahead of time to save time

In [ ]:
def compute_umap_projection(
    df,
    tfidf_matrix,
    n_svd_components=100,
    n_neighbors=15,
    min_dist=0.1,
    random_state=42
):
    svd = TruncatedSVD(
        n_components=n_svd_components,
        random_state=random_state
    )

    coords_svd = svd.fit_transform(tfidf_matrix)

    print(f"SVD output shape: {coords_svd.shape}")
    print(f"Variance explained: {svd.explained_variance_ratio_.sum():.2%}")

    reducer = umap.UMAP(
        n_components=3,
        n_neighbors=n_neighbors,
        min_dist=min_dist,
        metric="cosine",
        random_state=random_state
    )

    coords_umap = reducer.fit_transform(coords_svd)

    plot_df = pd.DataFrame({
        "x": coords_umap[:, 0],
        "y": coords_umap[:, 1],
        "z": coords_umap[:, 2],
        "name": df["name"].values,
        "decodedName": df["decodedName"].values,
    })

    return plot_df, svd, reducer

### Plotting function against umap

In [ ]:
def plot_similar_people_umap(
    plot_df_umap,
    reference_person,
    ref_idx,
    similar_indices
):
    plot_df = plot_df_umap.copy()

    plot_df["highlight"] = "Other"
    plot_df.loc[similar_indices, "highlight"] = "Top 10 Similar"
    plot_df.loc[ref_idx, "highlight"] = "Reference"

    fig = px.scatter_3d(
        plot_df,
        x="x",
        y="y",
        z="z",
        color="highlight",
        hover_name="decodedName",
        hover_data={
            "name": True,
            "x": False,
            "y": False,
            "z": False,
        },
        color_discrete_map={
            "Reference": "red",
            "Top 10 Similar": "orange",
            "Other": "lightblue",
        },
        title=f"UMAP 3D — {reference_person} and Top 10 Similar People",
        opacity=0.5,
    )

    fig.update_traces(marker_size=3)
    fig.update_traces(marker_size=10, selector={"name": "Top 10 Similar"})
    fig.update_traces(
        marker_size=10,
        marker_symbol="diamond",
        selector={"name": "Reference"}
    )

    fig.show()

In [ ]:
def get_similarity_results(reference_person, df, tfidf_matrix, top_n=10):
    ref_matches = df[df["name"] == reference_person].index

    if len(ref_matches) == 0:
        print(f"'{reference_person}' not found.")
        return None, None, None

    ref_idx = ref_matches[0]

    cosine_scores = cosine_similarity(
        tfidf_matrix[ref_idx],
        tfidf_matrix
    ).flatten()

    similar_indices = cosine_scores.argsort()[::-1]
    similar_indices = [i for i in similar_indices if i != ref_idx][:top_n]

    results = df.iloc[similar_indices][["name", "decodedName"]].copy()
    results["cosine_similarity"] = cosine_scores[similar_indices].round(4)

    results = results.reset_index(drop=True)
    results.index += 1

    return results, ref_idx, similar_indices

In [ ]:
def print_bios(results, df, max_chars=None):

    """

    Print biographies for people in a similarity results dataframe.

    Parameters

    ----------

    results : DataFrame

        Output from find_similar_people()

    df : DataFrame

        Original dataframe containing name and text columns

    max_chars : int or None

        Truncate bios for easier reading

    """

    for rank, row in results.iterrows():

        person = row["name"]

        display_name = row["decodedName"]

        bio = df.loc[

            df["name"] == person,

            "text"

        ].iloc[0]

        if max_chars is not None:

            bio = bio[:max_chars] + "..."

        print("=" * 80)

        print(f"Rank {rank + 1}: {display_name}")

        print("=" * 80)

        print(bio)

        print("\n")

## Read in Data

In [ ]:
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Project.5-NLP/Data/NLP.csv'
df = pd.read_csv(url)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42786 entries, 0 to 42785
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   URI     42786 non-null  object
 1   name    42786 non-null  object
 2   text    42786 non-null  object
dtypes: object(3)
memory usage: 1002.9+ KB

In [ ]:
sample  = df.sample()
sample

,URI,name,text
25491,<http://dbpedia.org/resource/Brush_Shiels>,Brush Shiels,brendan ian brush shiels born in 1952 dublin i...

In [ ]:
reference_person = 'Tim Bartro'

## Add column with decoded names ( safe url encoding was used in dbpedia )

In [ ]:
from urllib.parse import unquote

decoded = df["name"].apply(unquote)
num_encoded = (df["name"] != decoded).sum()
print(f"{num_encoded:,} rows contain URL-encoded characters")

2,485 rows contain URL-encoded characters

In [ ]:
df["decodedName"] = df["name"].apply(unquote)

In [ ]:
changed = df[df["name"] != df["decodedName"]]
changed[["name", "decodedName"]].head(20)

                                      name                decodedName
35                    Freimut B%C3%B6rngen            Freimut Börngen
36                  Th%C3%BCring Br%C3%A4m               Thüring Bräm
73                 Marcel J. Melan%C3%A7on         Marcel J. Melançon
85                     Zvonimir Juri%C4%87             Zvonimir Jurić
122  Se%C3%A1n %C3%93g %C3%93 hAilp%C3%ADn          Seán Óg Ó hAilpín
129        L%C3%A1zaro C%C3%A1rdenas Batel      Lázaro Cárdenas Batel
148                       Ren%C3%A9 Froger                René Froger
166         Ant%C3%B3nio Castanheira Neves  António Castanheira Neves
182             Mike P%C3%A9rez (baseball)      Mike Pérez (baseball)
203               David Pastr%C5%88%C3%A1k             David Pastrňák
209                       Andr%C3%A9 Hurst                André Hurst
258             Leonardo %C3%81lvarez Romo      Leonardo Álvarez Romo
262                        Uffe Elb%C3%A6k                 Uffe Elbæk
313      Mart%C3%ADn Emilio Rodr%C3%ADguez    Martín Emilio Rodríguez
333             Ahmet G%C3%BCne%C5%9Ftekin           Ahmet Güneştekin
342             Camilo Nogueira Rom%C3%A1n      Camilo Nogueira Román
345                      J%C3%B6rg Fischer               Jörg Fischer
346               Vytautas %C5%A0ustauskas        Vytautas Šustauskas
382                   St%C3%A9phane Mottin            Stéphane Mottin
400                    Sergio Ram%C3%ADrez             Sergio Ramírez

In [ ]:
df.sample()

,URI,name,text,decodedName
9129,<http://dbpedia.org/resource/Jan_Tore_Odegard>,Jan Tore Odegard,jan tore odegard born 14 october 1940 is a nor...,Jan Tore Odegard

In [ ]:
changed.shape

(2485, 4)

## Setup TF-IDF Model on short Bio Info

In [ ]:
# Vectorize the words with sklearn TFIDVectorizer
vectorizer = TfidfVectorizer(stop_words='english', max_features=10000)
tfidf_matrix = vectorizer.fit_transform(df['text'])
print(f'Matrix shape: {tfidf_matrix.shape}')  # (people, unique words)

Matrix shape: (42786, 10000)

In [ ]:
# Change this to any name from data frame
reference_person = "Bruce Taylor (baseball)"

In [ ]:
results = find_similar_people(
    reference_person=reference_person,
    df=df,
    tfidf_matrix=tfidf_matrix,
    top_n=10

)

results

,name,decodedName,cosine_similarity,euclidean_distance,cosine_rank,euclidean_rank,rank_difference,polarity,subjectivity,sentiment
1,Don Secrist,Don Secrist,0.3977,1.0976,1,1,0,0.080,0.313,Neutral
2,Jim Stump,Jim Stump,0.3948,1.1002,2,2,0,0.126,0.365,Positive
3,Vern Geishert,Vern Geishert,0.3824,1.1114,3,3,0,0.013,0.325,Neutral
4,John Tsitouris,John Tsitouris,0.3754,1.1177,4,4,0,0.044,0.382,Neutral
5,Jamie Brewington,Jamie Brewington,0.3740,1.1189,5,5,0,0.040,0.418,Neutral
6,Randor Bierd,Randor Bierd,0.3718,1.1209,6,6,0,0.098,0.287,Neutral
7,Rick Grapenthin,Rick Grapenthin,0.3687,1.1237,7,7,0,0.059,0.334,Neutral
8,Tom Flanigan (baseball),Tom Flanigan (baseball),0.3670,1.1252,8,8,0,0.013,0.228,Neutral
9,Jim Duffalo,Jim Duffalo,0.3628,1.1289,9,9,0,0.082,0.289,Neutral
10,Steve Kline (right-handed pitcher),Steve Kline (right-handed pitcher),0.3577,1.1334,10,10,0,0.067,0.260,Neutral

In [ ]:
print_bios(results, df)

================================================================================
Rank 2: Don Secrist
================================================================================
donald laverne secrist born february 26 1944 is an american former professional baseball player a lefthanded pitcher who appeared in 28 games played all in relief for the 19691970 chicago white sox of major league baseball he stood 6 feet 2 inches 188 m tall and weighed 195 pounds 88 kgsecrist had two outstanding seasons in minor league baseball after signing with the baltimore orioles he was undefeated in seven decisions with a 196 earned run average for the 1963 aberdeen pheasants of the class a northern league drafted from the orioles by the cincinnati reds following that season secrist spent five more years in the reds farm system in his last in 1968 he won 11 games and lost two for the indianapolis indians of the triplea pacific coast league following that campaign he was dealt with catcher don pavletich to the white sox for pitcher jack fishersecrist then spent much of the 1969 season with the mlb white sox appearing in 19 games making his debut during the home opener of the expansion seattle pilots at sicks stadium in his native city he recorded his only mlb decision a loss on july 16 against the minnesota twins secrist pitched four innings that day and allowed only two runs but he gave up the gamewinning tally on a home run by minnesotas rich reese in 1970 he appeared in nine more games for the chisox during april may and june before returning to the minor leagues in 28 games and 54 innings pitched at a major leaguer secrist allowed 54 hits nine home runs and 26 bases on balls with 32 strikeouts


================================================================================
Rank 3: Jim Stump
================================================================================
james gilbert stump born february 10 1932 is an american former professional baseball player who appeared in 11 major league baseball games as a relief pitcher for the 1957 and 1959 detroit tigers he threw and batted righthanded stood 6 feet 18 m tall and weighed 188 pounds 85 kgstump signed with the tigers in 1951 and his first two minor league seasons sandwiched around a twoyear military stint during the korean war were noteworthy as he won 30 of 43 decisions 698 after winning 14 games for the 1957 birmingham barons of the doublea southern association stump made his major league debut for the tigers against the boston red sox at briggs stadium working one inning in relief and giving up a hit a run and two bases on balls including one to ted williams in a 61 tiger defeat but overall stumps first trial with detroit was successful he appeared in five more games played won his only decision and surrendered a total of only three earned runs in 13 innings for a sparkling 208 earned run averagethe next two seasons stump put up identical 811 records with the triplea charleston senators before receiving his second and final audition with the tigers in 1959 pitching in 11 innings and posting another strong era 238 he played two more seasons of minor league ball ironically posting a third straight 811 season in the american association in 1960 and retired after the 1961 campaign


================================================================================
Rank 4: Vern Geishert
================================================================================
vernon william geishert born january 10 1946 is an american former professional baseball player a 6 ft 1 in 185 m 215 lb 98 kg righthanded pitcher he appeared in 11 major league baseball games for the california angels in 1969geishert was drafted by the angels in the second round of the january 1966 major league baseball draft out of the university of wisconsin madison after his fourth minor league campaign he was recalled by the angels in august 1969 in his debut against the cleveland indians he entered the game in relief of starting pitcher steve kealey in the third inning the angels were leading 42 but the indians were rallying and the bases were loaded geishert got vern fuller on a fly ball out and went on to pitch four full innings of threehit relief to earn the eventual 84 victory in his first mlb game he appeared in ten more games over the final weeks of the 1969 season including three starting assignments he gave up 32 hits and seven bases on balls in 31 total innings pitched with 18 strikeouts he was credited with one saveduring the offseason geshert was included in a major interleague trade going to the cincinnati reds with starting pitcher jim mcglothlin for hardhitting outfielder alex johnson and infielder chico ruiz but geishert never appeared in an mlb game for cincinnati spending two seasons at the triplea level before leaving the game


================================================================================
Rank 5: John Tsitouris
================================================================================
john philip tsitouris born may 4 1936 in monroe north carolina is an american former professional baseball player who pitched in the major leagues from 19571960 and 19621968 he threw and batted righthanded stood 6 feet 18 m tall and weighed 175 pounds 79 kgtsitouris graduated from benton heights high school in monroe north carolina he signed with the detroit tigers as an amateur free agent in 1954 and made his mlb debut with the tigers on june 13 1957 coming into a scoreless tie in relief of steve gromek in the fifth inning of a game against the baltimore orioles he had an adventurous top of the sixth frame surrendering two hits and a stolen base but emerged unscathed when oriole baserunners joe durham and dick williams were both thrown out at home plate then in detroits half of the sixth inning the tigers scored two runs on a home run by charlie maxwell and an rbi double by j w porter tsitouris pitched 1 innings that day and gave up one earned run three hits and two bases on balls but ended up getting credit for a 21 victory during that offseason he was part of a 13player trade that sent among others billy martin to the tigers from the kansas city athleticstsitouris had trials with the athletics in both 1958 and 1959 and spent all of 1960 on the kansas city roster but he appeared in only 14 games and 33 innings pitched and was traded to the cincinnati reds in a waiver deal for lefthanded pitcher joe nuxhall in january 1961 he spent almost two full seasons in minor league baseball before getting his chance with cincinnati in september 1962 tsitouris made the most of it giving up only two earned runs in 21 innings and hurling a complete game fivehit shutout against the philadelphia phillies on september 30for the next three seasons tsitouris was a fulltime member of the reds pitching staff winning 12 1963 nine 1964 and six 1965 games mostly as a starting pitcher on september 21 1964 he shut out the phillies 10 on six hits at connie mack stadium starting the tengame philadelphia losing streak that knocked the phillies out of first place however with his effectiveness diminishing yearbyyear tsitouris was sent to the triplea buffalo bisons in 1966 and despite brief trials with cincinnati in 19671968 spent the rest of his career in the minorshis major league record included 149 games pitched 34 wins three saves and 432 strikeouts in 663 inningshe currently lives in monroe north carolina


================================================================================
Rank 6: Jamie Brewington
================================================================================
jamie chancellor brewington born september 28 1971 in greenville north carolina is an american former major league baseball player the righthanded pitcher played for the san francisco giants in 1995 and the cleveland indians in 2000 he stood 6 feet 4 inches 193 m tall and weighed 180 pounds 82 kg during his active careerbrewington attended junius h rose high school in greenville and virginia commonwealth university selected by the giants in the tenth round of the 1992 major league baseball draft brewington was recalled from the doublea shreveport captains in july 1995 and made 13 starts from july 24 through seasons end he won his first two major league starts on july 24 against the florida marlins and july 30 against the eventual 1995 world champion atlanta braves altogether as a rookie he compiled a 64 winloss record allowing 68 hits including eight home runs in 75 innings pitched he had the same number of walks and strikeouts 45however brewington failed to make the 1996 giants and was ineffective in triplea posting a 69 record and poor 702 era with the phoenix giants he then was traded to the kansas city royals during the offseason his struggles continued during the 1997 minor league campaign with his earned run average ballooning to 784 in 23 games pitched he was traded to the milwaukee brewers organization on july 29 and then released on april 25 1998 brewington did not pitch professionally during the 1998 seasonhe then signed with the indians and struggled through another difficult season in the minors in 1999 going 110 with the class a kinston indians but brewington lowered his era to a respectable 384 and earned a promotion in 2000 to the indians triplea affiliate the buffalo bisons of the international league pitching exclusively in relief for the 2000 bisons he won his only decision and further improved his earned run average to 302 cleveland recalled him in june and used him in 26 games all in relief brewington won his three decisions with cleveland with no losses but allowed 56 hits and 19 walks in 45 innings pitched he struck out 34 he had no saves and his era was a high 536granted free agency at the end of the 2000 season brewington signed with the minnesota twins but never returned to the majors he spent his last year in minor league baseball in 2002 then played one more professional season in the independent leagues in 2004he remains in baseball as a scout for the pittsburgh piratesas a major leaguer brewington won nine games losing four 692 with an era of 485 in 39 games and 120 innings pitched he gave up 124 hits and 64 bases on balls striking out 79


================================================================================
Rank 7: Randor Bierd
================================================================================
randor bierd born march 14 1984 is a former major league baseball relief pitcherbierd was originally signed by the detroit tigers as an undrafted free agent on june 3 2003bierds best season in the tigers organization came in 2007 when he pitched for the singlea west michigan whitecaps and the doublea erie seawolves pitching in a total of 42 games 3 of which were starts bierd went 43 with a 293 eraon december 6 2007 bierd was selected by the baltimore orioles as the third overall pick in the major league phase of the rule 5 draft bierd made the orioles 2008 opening day roster as a relief pitcher on april 2 2008 bierd made his major league debut against the tampa bay rays and pitched two scoreless innings and was later placed on the 15day disabled liston january 19 2009 bierd was traded to the boston red sox for david pauley bierd spent the 2009 baseball season with the triplea pawtucket red sox achieving a 31 record with a 455 era as both a starter and reliever bierd spent the 20092010 offseason pitching winter baseball in the dominican league for leones del escogidoon july 22 2010 bierd was released by boston


================================================================================
Rank 8: Rick Grapenthin
================================================================================
richard ray grapenthin born april 16 1958 is an american former professional baseball player a righthanded pitcher who appeared in 19 major league games 18 in relief for the montreal expos for parts of three seasons between 1983 and 1985the 6 ft 2 in 188 m 185 lb 84 kg grapenthin played collegiately at indiana state university and was signed as an undrafted free agent by montreal on july 9 1980 he progressed through the montreal system posting a microscopic 080 earned run average in 45 innings pitched for the class a san jose expos of the california league in 1982 he made his mlb debut on may 3 1983 starting pitcher scott sanderson retired the atlanta braves in order in the top of the first inning but on the third out he was spiked in the pitching hand by claudell washington and was forced to leave the game grapenthin relieved sanderson in the second and kept atlanta off the scoreboard for his first two innings but in his third frame he allowed a threerun home run to bob horner and a solo shot to chris chambliss and was tagged with the eventual 52 loss it was his only mlb appearance of 1983 he was sent back to the triplea wichita aeros and played out the season therethe 1984 campaign saw grapenthin spend the early months at triplea with the indianapolis indians but he was recalled by the expos in august and on august 5 1984 he made his second mlb appearance and only starting assignment at wrigley field against the chicago cubs in the third inning he surrendered a grand slam home run to keith moreland the key blow in a 43 montreal defeat however grapenthin went unscored upon in his next four relief appearances and was largely effective coming out of montreals bullpen for the rest of the season he earned saves on august 22 and september 5 and his only mlb victory on september 10 the win came when he relieved a beleaguered david palmer in the first inning against the pittsburgh pirates with only one out and four runs in and the bases loaded grapenthin retired the next two hitters then pitched scoreless 423 innings of scoreless onehit ball while montreal rallied at bat he left the game with the expos in the lead 84 and received credit for the victorygrapenthin pitched poorly in five games for the 1985 expos and was sent back to indianapolis ending his mlb career all told he allowed 36 hits and 16 bases on balls in his 34 mlb innings pitched with 16 strikeouts and two saves he later played at triplea for the san diego padres st louis cardinals detroit tigers and new york yankees organizations and concluded his minor league career in 1989 after ten professional seasons


================================================================================
Rank 9: Tom Flanigan (baseball)
================================================================================
thomas anthony flanigan born september 6 1934 at cincinnati ohio is a retired american professional baseball player a 6 ft 3 in 191 m 175 lb 79 kg lefthanded pitcher who appeared in three major league baseball games over the course of a sevenyear professional career two games for the 1954 chicago white sox and one for the 1958 st louis cardinalsflanigan began his third professional season at age 19 on the white sox mlb roster and appeared in two games both in relief allowing no runs and only one hit a single to frank bolling of the detroit tigers in 1 innings pitched after spending the rest of 1954 and all of 1955 through 1957 in minor league baseball he was selected in the winter 1957 rule 5 draft by the cardinals and began 1958 on their roster in his only national league appearance against the chicago cubs at busch stadium april 15 flanigan hurled one inning in relief and allowed two hits and one run the latter coming on a home run by cub catcher cal neeman he then was returned to the white sox indianapolis indians affiliate from which he had been draftedflanigan allowed three hits and one run in 2 mlb innings pitched with two bases on balls and no strikeouts in 246 minor league games from 19521958 he won 55 of 100 decisions


================================================================================
Rank 10: Jim Duffalo
================================================================================
james francis duffalo born november 25 1935 is an american former professional baseball player a righthanded relief pitcher duffalo played all or part of five seasons 196165 in major league baseball and 18 years in organized baseball as a whole he was a member of the 1962 national league champion san francisco giants but did not appear in the 1962 world serieslisted at 6 feet 1 inch 185 m and 175 pounds 79 kg duffalo entered the professional ranks as a member of the pittsburgh pirates farm system in 1955 winning 17 games as a rookie in the class d georgiaflorida league in 1955 then another 16 games in the class b carolina league the following season but the pirates sent him to the giants during the 1958 seasonduffalo made his major league debut on april 12 1961 for the giants in a 21 win over the pirates at candlestick park he entered the game with two on and two outs in the ninth inning against roberto clemente who grounded out to end the game and duffalo was credited with a save his best years were in 1963 and 1964 in 1963 he pitched 34 games with a 42 record and a 287 earned run average followed in 1964 with 35 games and a 51 record with a 292 era duffalo would play 119 of his 141 major league games in a san francisco uniformhe was traded to the cincinnati reds for lefthanded relief specialist bill henry on may 4 1965 in 22 games he was 00 with a 345 era in what would be his last major league season however he spent another seven seasons in minor league baseball before his retirement in 1972 at age 36he compiled a 158 record with six saves and an era of 339 during his mlb career starting 14 games all for the giants and relieving in 127 games in 29723 innings pitched he allowed 238 hits and 155 bases on balls with 210 strikeoutsas a minor league hurler duffalo was 11072 with an era of 348 in 387 games and 1655 innings pitched he briefly coached in the giants farm system after his playing career ended


================================================================================
Rank 11: Steve Kline (right-handed pitcher)
================================================================================
steven jack kline born october 6 1947 is an american former professional baseball player a former starting pitcher who appeared in major league baseball from 1970 through 1974 and in 1977 listed at 6 feet 3 inches 191 m tall and 200 pounds 91 kg kline batted and threw righthandedkline was originally drafted by the new york yankees in the seventh round of the 1966 mlb draft he was 22 years old when he reached the majors in 1970 with the yankees spending four and a half years with them before moving to the cleveland indians 1974 and atlanta braves 1977 in his rookie season for the yankees he went 66 with a 341 era in 15 starts and won 12 games a year later including careernumbers with 81 strikeouts and 15 complete gameshis most productive season came in 1972 when he recorded careerhighs in wins 16 era 240 starts 32 shutouts 4 and innings pitched 236 he declined after that and was sent to cleveland in a major early season 1974 trade that sent chris chambliss and dick tidrow to the bronx kline missed the 1975 season with arm problems and spent 1976 back in minor league baseball before making 16 relief appearances for atlanta in 1977 his last major league seasonin a sixseason mlb career kline posted a 4345 record with 240 strikeouts and a 326 era in 750 innings and 129 games pitched 105 as a starter he allowed 708 hits and 184 bases on ballshe now is a pitching coach at wenatchee high school 4a in wa

In [ ]:
plot_df_umap, svd_model, umap_model = compute_umap_projection(

    df,

    tfidf_matrix

)

SVD output shape: (42786, 100)
Variance explained: 16.63%

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

In [ ]:
reference_person = "Bruce Taylor (baseball)"
results, ref_idx, similar_indices = get_similarity_results(

    reference_person,
    df,
    tfidf_matrix,
    top_n=10

)

print(results)

plot_similar_people_umap(

    plot_df_umap,
    reference_person,
    ref_idx,
    similar_indices

)

                                  name                         decodedName  \
1                          Don Secrist                         Don Secrist
2                            Jim Stump                           Jim Stump
3                        Vern Geishert                       Vern Geishert
4                       John Tsitouris                      John Tsitouris
5                     Jamie Brewington                    Jamie Brewington
6                         Randor Bierd                        Randor Bierd
7                      Rick Grapenthin                     Rick Grapenthin
8              Tom Flanigan (baseball)             Tom Flanigan (baseball)
9                          Jim Duffalo                         Jim Duffalo
10  Steve Kline (right-handed pitcher)  Steve Kline (right-handed pitcher)

    cosine_similarity
1              0.3977
2              0.3948
3              0.3824
4              0.3754
5              0.3740
6              0.3718
7              0.3687
8              0.3670
9              0.3628
10             0.3577

## Issues/Observation - Some people are matched on country of origin rather than occupation. This may not be the bias we want

In [ ]:
reference_person_1 = "Iradj Fazel"

results_1, ref_idx_1, similar_indices_1 = get_similarity_results(

    reference_person_1,
    df,
    tfidf_matrix,
    top_n=10

)


display(results_1)

plot_similar_people_umap(

    plot_df_umap,
    reference_person,
    ref_idx_1,
    similar_indices_1

)

                       name              decodedName  cosine_similarity
1    Maziar Ashrafian Bonab   Maziar Ashrafian Bonab             0.4630
2                 Sima Bina                Sima Bina             0.4437
3   Mohammad Reza Azadehfar  Mohammad Reza Azadehfar             0.4104
4    Moslem Eskandar-Filabi   Moslem Eskandar-Filabi             0.4103
5            Maryam Akhondy           Maryam Akhondy             0.4032
6            Sadegh Kharazi           Sadegh Kharazi             0.4028
7              Mahsa Vahdat             Mahsa Vahdat             0.3673
8           Hossein Marashi          Hossein Marashi             0.3639
9      Hassan Shariatmadari     Hassan Shariatmadari             0.3559
10           Firoozeh Dumas           Firoozeh Dumas             0.3557

In [ ]:
print_bios(results_1,df)

================================================================================
Rank 2: Maziar Ashrafian Bonab
================================================================================
dr maziar ashrafian bonab persian is an iranian forensic and medical geneticistspecialising in forensic genetics the use of the dna markers in the investigation of crimes and ancestry and forensic facial reconstruction his groundbreaking research uses human dna markers mainly mtdna and the y chromosome markers to identify the ancestral history of humanshuman populations in both anthropological and forensic cases his main area of research is the population history of the middle east specifically iranmaziar was born in tehran iran 20 september 1966 before completing his phd in cambridge he first qualified as a medical doctor from tehran university of medical sciences 19841991 and worked as a medical practitioner in iran after completing a postgraduate course in forensic medicine at the iranian legal medical organization 1992 he worked as the head of hormozgan province legal medical centre iran for four years 19921996 as well as dealing with many different forensic cases and having done more than 400 autopsies he taught forensic medicine and medical anthropology to the undergraduate and postgraduate degree programmes within the bandarabbas university of medical sciences and bandarabbas islamic azad universitysince 1996 to 2002 he worked as an academic member of the iranian archaeological research centre at the cultural heritage organization of iran icho and as a forensic anthropologist he participated in seventeen archaeological excavations around iranat the same time as the founder and head of the national museum of medical sciences history iran he established the first medical museum in the country and the largest one in the middle east in 2003 he completed an msc degree in archaeology 20022003 at the department of biomolecular sciences university of manchester institute of science and technology and in october 2003 he started a phd in the field of biological anthropologyhuman population genetics at the university of cambridge since 2006 he has been working as a senior lecturer at the school of biological sciences university of portsmouth he has published various books and papers on his researchin his current research he is using genetic tools to investigate the maternal and paternal history of the iranian ethnic groups and also the emergence of first farmers in the iranian plateau eastern parts of the fertile crescent and the origin of aryans indoiranians and indoaryan race theory


================================================================================
Rank 3: Sima Bina
================================================================================
sim bin persian born january 4 1945 in birjand iran is notable persian classical musician an iranian composer researcher painter and teacher described by radio wdr germany as the grand lady of iranian folk music a leading iranian classical singer and songwriter a lifetime of dedicated work on persian folk music has made master sima bina a legendary character in the history of iranian musicsince 1993 she has accepted invitations to perform her music worldwide in prestigious festivals and organized concerts persian classical musician she is currently living in cologne germany and tehran iranmaster sima binas career in the performing arts has spanned 5 decades born in khorasan in the heart of a popular tradition she started her career on iranian radio at the age of nine under the direction of her father ahmad bina a master of iranian classical music and poet who wrote many of her early songsshe studied the repertoire of learned music radif and singing technique with great masters such as maaroufi and zarrin panjeh she went on to acquire her own solo programme golhaye sahraii flowers of the desert presenting a collection of folk songs and music from various regions of iran which is still remembered todayafter graduating from tehran university in 1969 majoring in fine arts sima bina contniued and perfected her knowledge of radif with the highly subtle teaching of great master davamiher main focus is iranian folk and classic music master bina has been able to gather and revive a collection of almost forgotten iranian folk songs and melodies a captivating vocalist master sima bina is one of the leading exponents of the traditional music of iran for decades she has done extensive research on persian folk songs collecting recording writing and reinterpreting popular regional music her works cover the whole spectrum of iranian folk music including mazandarani music kurdish music turkmen music baloch music lor music shirazi music afghan music bakhtiari music north and south khorasaniranian lullabieswhile pursuing iranian folksongs master sima bina often came across a variety of ethnic lullabies which she added to her collected works this collection finally led to her book iranian lullabies in 2009 in this book master sima bina not only shares her findings her perception the scores and visual expression of the selected lullabies with mothers she also presents fouty original iranian lullabies in four cds in which her vocal is sometimes blended with the singing of the mothers who had song the lullabies to her in different parts of iranthe worldwide recognition her music receives today is the materialization of over forty years of her devotion to iranian musicmaster sima binas music feeds my soul the gilded serpentshe has gained a unique position in the history of persian music world music central


================================================================================
Rank 4: Mohammad Reza Azadehfar
================================================================================
mohammad reza azadehfar persian ethnomusicologist and santr performer born in 1969 in isfahan the safavid capital of iran he started learning iranian traditional dulcimer santr under the supervision of said naimimanesh in 1981 and spent some 4 years at conservatory of isfahan in 1988 he immigrated to tehran and attended faramarz payvar santr lecture conducted by faramarz payvar and said sabetazadehfar also interested on film studies he studied cinema at iranian youth cinema society in 1982 and in 1988 he entered the faculty of cinema and theater at tehran university of arts to take a ba in cinema his special interest in cinema was film scoring and editing azadehfar won the prize of best film scoring in 1987 for a short film by asghar farhadi and a prize for best editing in 1993 at the national festival of cinema javansince 1993 azadehfar mainly focused on theoretical issues of iranian music he began his studies by attending an ma program in research of arts in tehran working on the topic of general training of iranian music his dissertation later on published as a book in persian language and sold more than 5000 copies rhythm specially was interesting to azadehfar he learned iranian percussion instrument tombak and moved to sheffield in england to do a phd program in the subject of rhythmic structure in iranian music in 1999 he finished his phd program in 2003 and admitted a postdoc program in soas university of london at the same year he finished his fellowship in soas in 2005 and returned to iranin 2005 azadehfar took a job as a faculty member of music faculty in tehran university of art in 2010 he was elected as a dean of music faculty until 2014 meantime he established ethnomusicology program in this faculty and spent years teaching there he is now an associate professor in this facultyin 2014 the executive board of ictm international council for traditional music appointed azadehfar as ictm liaison officer for iran


================================================================================
Rank 5: Moslem Eskandar-Filabi
================================================================================
moslem eskandarfilabi persian born 26 march 1944 in filab quchan county razavi khorasan province iran more known as eskandar filabi is a renowned iranian wrestler in the 1960s and 1970s he is among the most successful iranian athletes with 4 gold medals at the 1966 1970 and 1974 asian gamesfilabi also represented iran in three olympics 1968 mexico city 1972 munich germany and 1976 montreal canada he was the flag carrier for the iranian olympic delegation carrying the flag with only one handhe left iran after islamic revolution and joined the parliamentinexile national council of resistance of iranhe has a special arm band as an iranian national hero he also has a total of 17 gold silver and bronze medals which he received from international gamesmr filabi is the record holder among iranian wrestlers for the asian games he has 4 gold medals from wrestling in 3 asian games he is also the only iranian wrestler who wrestled and won a medal in 5 styles of wrestling freestyle grecoroman sambo pahlevanistyle and chookheh an ethnicstyle traditional to northern iranhe has a ba from teachers training college in iran doneshsarayeh aleh ma from george washington university after his wrestling career he was a dean of physical education at the university of ferdowsi mashad iran


================================================================================
Rank 6: Maryam Akhondy
================================================================================
maryam akhondy born 1957 is a classical trained singer from tehran iran she was student of ostad esmail mehrtasch and ostad nassrollah nassehpour two masters of classical iranian music because of the difficult situation for artists especially female artists in iran after the islamic revolution of 1979 she moved to europe and since 1986 has lived in cologne germanyafter 1986 maryam akhondy started working with other iranian musicians in exile with nawa and tschakawak two groups of traditional iranian musicians she performed in germany and scandinaviaat the same time she founded ensemble barbad a group with three to five musicians all classical trained artists barbad has been touring all over europe for the past years maryam akhondy and ensemble barbads newest project is called sarmast which means intoxicated in this case intoxicated by the lyrics of the great iranian poets such as hafez and others sarmast is akhondys own compositions in the style of classical persian art and music the cd sarmast iranian art music for texts of persian poets was published in 2006between 1999 and 2000 maryam akhondy created an allfemale acapella group banu because in iran it is difficult for female singers to appear publicly only for religious rituals called tazieh are they allowed to make music furthermore for men it is forbidden to listen to the singing of women therefore for iranian women singing is possible only in private sphere where women are alone or among themselves at the cradle doing housework working in the fields and womens celebrations maryam akhondy made it her business to bring traditional womens songs back to life again over the years she has been collecting songs and published them in 2004 on her album banu songs of persian womenbanu named after the persian word for noble lady or distinguished lady is a kind of musical expedition to the different regions and cultures of iran it gives an informative view of the singing culture and selfconfidence of the persian women most of these songs are full of life and energy accompanied by various percussion instruments this is quite unusual for iranian music which is often more serene and melancholic but these old folk songs are funny ironic and give a view of the iranian woman when she is in private the women of banu have been touring in europe turkey and tunisia until 2012maryam akhondys creative work includes the research of old persian music of the preislamic age as well in her musical creation music in praise of ahura mazda she merges traditional iranian art music and lyrics which has to do with the old zoroastrian religion and philosophy first performances had been at musica sacra international festival 2012 in fssen isny and kaufbeuren germanymaryam akhondy as a soloist has also done noniranian collaborations with the schl sick brass band of cologne between 1994 and 1999 with mike herting during the ruhrtriennale in 2008 and with bobby mcferrin in 2009


================================================================================
Rank 7: Sadegh Kharazi
================================================================================
seyed mohammad sadegh kharazi born 2 march 1963 is a former iranian diplomat and advisor to irans former president khatamikharazi started his career in 1983 during the iraniraq war in the high defence council and the irib he subsequently became irans ambassador to the united nations in 1989 and after a period of six years he returned to iran as deputy foreign minister for research he became irans ambassador to france in 2002 until 2006 when mahmoud ahmadinejad was elected into office kharazi was the chairman of the 1997 tehran oic summit he was also a key figure in the twoyear nuclear negotiations with the eu triokharazi has a keen interest in calligraphic and historical manuscripts and is an avid collector of such items he is a member of the board of several iranian cultural educational and research centers including tehran university the cultural heritage organization of iran and the national library of irancurrently kharazi works closely with mohammad khatami on the issue of dialogue amongst civilizations and is his senior advisor he is the co founder of the encyclopedia of contemporary islam that researches the cultural and political movements and schools of thought of iran in the past two centuries additionally he is the founder and editor of the iranian diplomacy website the iranian economy website and heritage of iran and islam website


================================================================================
Rank 8: Mahsa Vahdat
================================================================================

# Part 2)

- For the same reference person that you chose in Part 1), use the Wikipedia API to access the whole content of the reference person's Wikipedia page.
- The goal of Part 2) is to ...
  1. Print out the text of the Wikipedia article for the reference person
  1. Determine the sentiment of the text of the Wikipedia page for the reference person
  1. Collect the text of the Wikipedia pages from the 10 nearest neighbors from Part 1)
  1. Determine the nearness ranking of these 10 people to your reference person based on their entire Wikipedia page
  1. Compare, i.e. plot,  the nearest ranking from Step 1) with the Wikipedia page nearness ranking.  A difference of the rank is one means of comparison.

In [ ]:
%%capture
!pip3 install wikipedia-api
import wikipediaapi

wiki = wikipediaapi.Wikipedia(language='en', user_agent='Project5/1.0')

def get_wiki_text(name):
    page = wiki.page(name)
    if page.exists():
        return page.text
    return ""

ref_wiki_text = get_wiki_text(reference_person)
print(f"Wikipedia article length: {len(ref_wiki_text.split())} words\n")
print(ref_wiki_text[:3000])

In [ ]:
from textblob import TextBlob

blob = TextBlob(ref_wiki_text)
polarity     = blob.sentiment.polarity
subjectivity = blob.sentiment.subjectivity

label = 'Positive' if polarity > 0.1 else ('Negative' if polarity < -0.1 else 'Neutral')

print(f"Wikipedia Sentiment for: {reference_person}")
print(f"  Polarity:     {polarity:.3f}  ({label})")
print(f"  Subjectivity: {subjectivity:.3f}  ({'Subjective' if subjectivity > 0.5 else 'Objective'})")

Wikipedia Sentiment for: Bruce Taylor (baseball)
  Polarity:     0.122  (Positive)
  Subjectivity: 0.474  (Objective)

In [ ]:
neighbor_names = df.iloc[similar_indices]['name'].tolist()

wiki_texts = {}
for name in neighbor_names:
    text = get_wiki_text(name)
    wiki_texts[name] = text
    status = f"{len(text.split())} words" if text else "NOT FOUND"
    print(f"  {name}: {status}")

  Don Secrist: 358 words
  Jim Stump: 320 words
  Vern Geishert: 260 words
  John Tsitouris: 475 words
  Jamie Brewington: 477 words
  Randor Bierd: 308 words
  Rick Grapenthin: 489 words
  Tom Flanigan (baseball): 265 words
  Jim Duffalo: 391 words
  Steve Kline (right-handed pitcher): 303 words

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

corpus_names = [reference_person] + neighbor_names
corpus_texts = [ref_wiki_text] + [wiki_texts[n] for n in neighbor_names]

wiki_vectorizer = TfidfVectorizer(stop_words='english', max_features=10000)
wiki_matrix = wiki_vectorizer.fit_transform(corpus_texts)

wiki_sims = cosine_similarity(wiki_matrix[0], wiki_matrix[1:]).flatten()

comparison_df = pd.DataFrame({
    'name': neighbor_names,
    'dbpedia_rank': range(1, 11),
    'wiki_similarity': wiki_sims,
})

comparison_df['wiki_rank'] = comparison_df['wiki_similarity'].rank(ascending=False).astype(int)
comparison_df['rank_change'] = comparison_df['dbpedia_rank'] - comparison_df['wiki_rank']
print(comparison_df.to_string(index=False))

                              name  dbpedia_rank  wiki_similarity  wiki_rank  rank_change
                       Don Secrist             1         0.163162          4           -3
                         Jim Stump             2         0.182715          3           -1
                     Vern Geishert             3         0.119482         10           -7
                    John Tsitouris             4         0.140681          8           -4
                  Jamie Brewington             5         0.153645          7           -2
                      Randor Bierd             6         0.131788          9           -3
                   Rick Grapenthin             7         0.156597          6            1
           Tom Flanigan (baseball)             8         0.160185          5            3
                       Jim Duffalo             9         0.193802          2            7
Steve Kline (right-handed pitcher)            10         0.231585          1            9

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=comparison_df['name'], y=comparison_df['dbpedia_rank'],
    mode='lines+markers', name='DBpedia Rank',
    marker=dict(size=10, color='steelblue'),
))

fig.add_trace(go.Scatter(
    x=comparison_df['name'], y=comparison_df['wiki_rank'],
    mode='lines+markers', name='Wikipedia Rank',
    marker=dict(size=10, color='coral'),
))

fig.update_layout(
    title=f'DBpedia vs Wikipedia Ranking — relative to {reference_person}',
    xaxis_title='Person',
    yaxis_title='Rank (1 = most similar)',
    yaxis=dict(autorange='reversed'),
    xaxis_tickangle=45,
    height=500,
)
fig.show()

# Part 3)

Make an interactive notebook where a user can choose or enter a name and the notebook displays the 10 closest individuals.

In addition to presenting the project slides, at the end of the presentation each student will demonstrate their code using a famous person suggested by the other students that exists in the DBpedia set.

In [ ]:
import ipywidgets as widgets
from IPython.display import display

name_options = sorted(df["decodedName"].dropna().unique().tolist())

person_picker = widgets.Combobox(
    placeholder="Type a famous person...",
    options=name_options,
    description="Person:",
    #ensure_option=True,
    layout=widgets.Layout(width="500px")
)

def set_reference_person(decoded_name):
    global reference_person

    if decoded_name:
        reference_person = df.loc[
            df["decodedName"] == decoded_name,
            "name"
        ].iloc[0]

        print(f"reference_person set to: {reference_person}")

widgets.interact(
    set_reference_person,
    decoded_name=person_picker
);

interactive(children=(Combobox(value='', description='Person:', layout=Layout(width='500px'), options=(' Renat…

In [ ]:
results, ref_idx, similar_indices = get_similarity_results(

    reference_person,

    df,

    tfidf_matrix,

    top_n=10

)

display(results)
print_bios(results, df)

plot_similar_people_umap(

    plot_df_umap,
    reference_person,
    ref_idx,
    similar_indices

)

,name,decodedName,cosine_similarity
1,Don Secrist,Don Secrist,0.3977
2,Jim Stump,Jim Stump,0.3948
3,Vern Geishert,Vern Geishert,0.3824
4,John Tsitouris,John Tsitouris,0.3754
5,Jamie Brewington,Jamie Brewington,0.3740
6,Randor Bierd,Randor Bierd,0.3718
7,Rick Grapenthin,Rick Grapenthin,0.3687
8,Tom Flanigan (baseball),Tom Flanigan (baseball),0.3670
9,Jim Duffalo,Jim Duffalo,0.3628
10,Steve Kline (right-handed pitcher),Steve Kline (right-handed pitcher),0.3577

================================================================================
Rank 2: Don Secrist
================================================================================
donald laverne secrist born february 26 1944 is an american former professional baseball player a lefthanded pitcher who appeared in 28 games played all in relief for the 19691970 chicago white sox of major league baseball he stood 6 feet 2 inches 188 m tall and weighed 195 pounds 88 kgsecrist had two outstanding seasons in minor league baseball after signing with the baltimore orioles he was undefeated in seven decisions with a 196 earned run average for the 1963 aberdeen pheasants of the class a northern league drafted from the orioles by the cincinnati reds following that season secrist spent five more years in the reds farm system in his last in 1968 he won 11 games and lost two for the indianapolis indians of the triplea pacific coast league following that campaign he was dealt with catcher don pavletich to the white sox for pitcher jack fishersecrist then spent much of the 1969 season with the mlb white sox appearing in 19 games making his debut during the home opener of the expansion seattle pilots at sicks stadium in his native city he recorded his only mlb decision a loss on july 16 against the minnesota twins secrist pitched four innings that day and allowed only two runs but he gave up the gamewinning tally on a home run by minnesotas rich reese in 1970 he appeared in nine more games for the chisox during april may and june before returning to the minor leagues in 28 games and 54 innings pitched at a major leaguer secrist allowed 54 hits nine home runs and 26 bases on balls with 32 strikeouts


================================================================================
Rank 3: Jim Stump
================================================================================
james gilbert stump born february 10 1932 is an american former professional baseball player who appeared in 11 major league baseball games as a relief pitcher for the 1957 and 1959 detroit tigers he threw and batted righthanded stood 6 feet 18 m tall and weighed 188 pounds 85 kgstump signed with the tigers in 1951 and his first two minor league seasons sandwiched around a twoyear military stint during the korean war were noteworthy as he won 30 of 43 decisions 698 after winning 14 games for the 1957 birmingham barons of the doublea southern association stump made his major league debut for the tigers against the boston red sox at briggs stadium working one inning in relief and giving up a hit a run and two bases on balls including one to ted williams in a 61 tiger defeat but overall stumps first trial with detroit was successful he appeared in five more games played won his only decision and surrendered a total of only three earned runs in 13 innings for a sparkling 208 earned run averagethe next two seasons stump put up identical 811 records with the triplea charleston senators before receiving his second and final audition with the tigers in 1959 pitching in 11 innings and posting another strong era 238 he played two more seasons of minor league ball ironically posting a third straight 811 season in the american association in 1960 and retired after the 1961 campaign


================================================================================
Rank 4: Vern Geishert
================================================================================
vernon william geishert born january 10 1946 is an american former professional baseball player a 6 ft 1 in 185 m 215 lb 98 kg righthanded pitcher he appeared in 11 major league baseball games for the california angels in 1969geishert was drafted by the angels in the second round of the january 1966 major league baseball draft out of the university of wisconsin madison after his fourth minor league campaign he was recalled by the angels in august 1969 in his debut against the cleveland indians he entered the game in relief of starting pitcher steve kealey in the third inning the angels were leading 42 but the indians were rallying and the bases were loaded geishert got vern fuller on a fly ball out and went on to pitch four full innings of threehit relief to earn the eventual 84 victory in his first mlb game he appeared in ten more games over the final weeks of the 1969 season including three starting assignments he gave up 32 hits and seven bases on balls in 31 total innings pitched with 18 strikeouts he was credited with one saveduring the offseason geshert was included in a major interleague trade going to the cincinnati reds with starting pitcher jim mcglothlin for hardhitting outfielder alex johnson and infielder chico ruiz but geishert never appeared in an mlb game for cincinnati spending two seasons at the triplea level before leaving the game


================================================================================
Rank 5: John Tsitouris
================================================================================
john philip tsitouris born may 4 1936 in monroe north carolina is an american former professional baseball player who pitched in the major leagues from 19571960 and 19621968 he threw and batted righthanded stood 6 feet 18 m tall and weighed 175 pounds 79 kgtsitouris graduated from benton heights high school in monroe north carolina he signed with the detroit tigers as an amateur free agent in 1954 and made his mlb debut with the tigers on june 13 1957 coming into a scoreless tie in relief of steve gromek in the fifth inning of a game against the baltimore orioles he had an adventurous top of the sixth frame surrendering two hits and a stolen base but emerged unscathed when oriole baserunners joe durham and dick williams were both thrown out at home plate then in detroits half of the sixth inning the tigers scored two runs on a home run by charlie maxwell and an rbi double by j w porter tsitouris pitched 1 innings that day and gave up one earned run three hits and two bases on balls but ended up getting credit for a 21 victory during that offseason he was part of a 13player trade that sent among others billy martin to the tigers from the kansas city athleticstsitouris had trials with the athletics in both 1958 and 1959 and spent all of 1960 on the kansas city roster but he appeared in only 14 games and 33 innings pitched and was traded to the cincinnati reds in a waiver deal for lefthanded pitcher joe nuxhall in january 1961 he spent almost two full seasons in minor league baseball before getting his chance with cincinnati in september 1962 tsitouris made the most of it giving up only two earned runs in 21 innings and hurling a complete game fivehit shutout against the philadelphia phillies on september 30for the next three seasons tsitouris was a fulltime member of the reds pitching staff winning 12 1963 nine 1964 and six 1965 games mostly as a starting pitcher on september 21 1964 he shut out the phillies 10 on six hits at connie mack stadium starting the tengame philadelphia losing streak that knocked the phillies out of first place however with his effectiveness diminishing yearbyyear tsitouris was sent to the triplea buffalo bisons in 1966 and despite brief trials with cincinnati in 19671968 spent the rest of his career in the minorshis major league record included 149 games pitched 34 wins three saves and 432 strikeouts in 663 inningshe currently lives in monroe north carolina


================================================================================
Rank 6: Jamie Brewington
================================================================================
jamie chancellor brewington born september 28 1971 in greenville north carolina is an american former major league baseball player the righthanded pitcher played for the san francisco giants in 1995 and the cleveland indians in 2000 he stood 6 feet 4 inches 193 m tall and weighed 180 pounds 82 kg during his active careerbrewington attended junius h rose high school in greenville and virginia commonwealth university selected by the giants in the tenth round of the 1992 major league baseball draft brewington was recalled from the doublea shreveport captains in july 1995 and made 13 starts from july 24 through seasons end he won his first two major league starts on july 24 against the florida marlins and july 30 against the eventual 1995 world champion atlanta braves altogether as a rookie he compiled a 64 winloss record allowing 68 hits including eight home runs in 75 innings pitched he had the same number of walks and strikeouts 45however brewington failed to make the 1996 giants and was ineffective in triplea posting a 69 record and poor 702 era with the phoenix giants he then was traded to the kansas city royals during the offseason his struggles continued during the 1997 minor league campaign with his earned run average ballooning to 784 in 23 games pitched he was traded to the milwaukee brewers organization on july 29 and then released on april 25 1998 brewington did not pitch professionally during the 1998 seasonhe then signed with the indians and struggled through another difficult season in the minors in 1999 going 110 with the class a kinston indians but brewington lowered his era to a respectable 384 and earned a promotion in 2000 to the indians triplea affiliate the buffalo bisons of the international league pitching exclusively in relief for the 2000 bisons he won his only decision and further improved his earned run average to 302 cleveland recalled him in june and used him in 26 games all in relief brewington won his three decisions with cleveland with no losses but allowed 56 hits and 19 walks in 45 innings pitched he struck out 34 he had no saves and his era was a high 536granted free agency at the end of the 2000 season brewington signed with the minnesota twins but never returned to the majors he spent his last year in minor league baseball in 2002 then played one more professional season in the independent leagues in 2004he remains in baseball as a scout for the pittsburgh piratesas a major leaguer brewington won nine games losing four 692 with an era of 485 in 39 games and 120 innings pitched he gave up 124 hits and 64 bases on balls striking out 79


================================================================================
Rank 7: Randor Bierd
================================================================================
randor bierd born march 14 1984 is a former major league baseball relief pitcherbierd was originally signed by the detroit tigers as an undrafted free agent on june 3 2003bierds best season in the tigers organization came in 2007 when he pitched for the singlea west michigan whitecaps and the doublea erie seawolves pitching in a total of 42 games 3 of which were starts bierd went 43 with a 293 eraon december 6 2007 bierd was selected by the baltimore orioles as the third overall pick in the major league phase of the rule 5 draft bierd made the orioles 2008 opening day roster as a relief pitcher on april 2 2008 bierd made his major league debut against the tampa bay rays and pitched two scoreless innings and was later placed on the 15day disabled liston january 19 2009 bierd was traded to the boston red sox for david pauley bierd spent the 2009 baseball season with the triplea pawtucket red sox achieving a 31 record with a 455 era as both a starter and reliever bierd spent the 20092010 offseason pitching winter baseball in the dominican league for leones del escogidoon july 22 2010 bierd was released by boston


================================================================================
Rank 8: Rick Grapenthin
================================================================================
richard ray grapenthin born april 16 1958 is an american former professional baseball player a righthanded pitcher who appeared in 19 major league games 18 in relief for the montreal expos for parts of three seasons between 1983 and 1985the 6 ft 2 in 188 m 185 lb 84 kg grapenthin played collegiately at indiana state university and was signed as an undrafted free agent by montreal on july 9 1980 he progressed through the montreal system posting a microscopic 080 earned run average in 45 innings pitched for the class a san jose expos of the california league in 1982 he made his mlb debut on may 3 1983 starting pitcher scott sanderson retired the atlanta braves in order in the top of the first inning but on the third out he was spiked in the pitching hand by claudell washington and was forced to leave the game grapenthin relieved sanderson in the second and kept atlanta off the scoreboard for his first two innings but in his third frame he allowed a threerun home run to bob horner and a solo shot to chris chambliss and was tagged with the eventual 52 loss it was his only mlb appearance of 1983 he was sent back to the triplea wichita aeros and played out the season therethe 1984 campaign saw grapenthin spend the early months at triplea with the indianapolis indians but he was recalled by the expos in august and on august 5 1984 he made his second mlb appearance and only starting assignment at wrigley field against the chicago cubs in the third inning he surrendered a grand slam home run to keith moreland the key blow in a 43 montreal defeat however grapenthin went unscored upon in his next four relief appearances and was largely effective coming out of montreals bullpen for the rest of the season he earned saves on august 22 and september 5 and his only mlb victory on september 10 the win came when he relieved a beleaguered david palmer in the first inning against the pittsburgh pirates with only one out and four runs in and the bases loaded grapenthin retired the next two hitters then pitched scoreless 423 innings of scoreless onehit ball while montreal rallied at bat he left the game with the expos in the lead 84 and received credit for the victorygrapenthin pitched poorly in five games for the 1985 expos and was sent back to indianapolis ending his mlb career all told he allowed 36 hits and 16 bases on balls in his 34 mlb innings pitched with 16 strikeouts and two saves he later played at triplea for the san diego padres st louis cardinals detroit tigers and new york yankees organizations and concluded his minor league career in 1989 after ten professional seasons


================================================================================
Rank 9: Tom Flanigan (baseball)
================================================================================
thomas anthony flanigan born september 6 1934 at cincinnati ohio is a retired american professional baseball player a 6 ft 3 in 191 m 175 lb 79 kg lefthanded pitcher who appeared in three major league baseball games over the course of a sevenyear professional career two games for the 1954 chicago white sox and one for the 1958 st louis cardinalsflanigan began his third professional season at age 19 on the white sox mlb roster and appeared in two games both in relief allowing no runs and only one hit a single to frank bolling of the detroit tigers in 1 innings pitched after spending the rest of 1954 and all of 1955 through 1957 in minor league baseball he was selected in the winter 1957 rule 5 draft by the cardinals and began 1958 on their roster in his only national league appearance against the chicago cubs at busch stadium april 15 flanigan hurled one inning in relief and allowed two hits and one run the latter coming on a home run by cub catcher cal neeman he then was returned to the white sox indianapolis indians affiliate from which he had been draftedflanigan allowed three hits and one run in 2 mlb innings pitched with two bases on balls and no strikeouts in 246 minor league games from 19521958 he won 55 of 100 decisions


================================================================================
Rank 10: Jim Duffalo
================================================================================
james francis duffalo born november 25 1935 is an american former professional baseball player a righthanded relief pitcher duffalo played all or part of five seasons 196165 in major league baseball and 18 years in organized baseball as a whole he was a member of the 1962 national league champion san francisco giants but did not appear in the 1962 world serieslisted at 6 feet 1 inch 185 m and 175 pounds 79 kg duffalo entered the professional ranks as a member of the pittsburgh pirates farm system in 1955 winning 17 games as a rookie in the class d georgiaflorida league in 1955 then another 16 games in the class b carolina league the following season but the pirates sent him to the giants during the 1958 seasonduffalo made his major league debut on april 12 1961 for the giants in a 21 win over the pirates at candlestick park he entered the game with two on and two outs in the ninth inning against roberto clemente who grounded out to end the game and duffalo was credited with a save his best years were in 1963 and 1964 in 1963 he pitched 34 games with a 42 record and a 287 earned run average followed in 1964 with 35 games and a 51 record with a 292 era duffalo would play 119 of his 141 major league games in a san francisco uniformhe was traded to the cincinnati reds for lefthanded relief specialist bill henry on may 4 1965 in 22 games he was 00 with a 345 era in what would be his last major league season however he spent another seven seasons in minor league baseball before his retirement in 1972 at age 36he compiled a 158 record with six saves and an era of 339 during his mlb career starting 14 games all for the giants and relieving in 127 games in 29723 innings pitched he allowed 238 hits and 155 bases on balls with 210 strikeoutsas a minor league hurler duffalo was 11072 with an era of 348 in 387 games and 1655 innings pitched he briefly coached in the giants farm system after his playing career ended


================================================================================
Rank 11: Steve Kline (right-handed pitcher)
================================================================================
steven jack kline born october 6 1947 is an american former professional baseball player a former starting pitcher who appeared in major league baseball from 1970 through 1974 and in 1977 listed at 6 feet 3 inches 191 m tall and 200 pounds 91 kg kline batted and threw righthandedkline was originally drafted by the new york yankees in the seventh round of the 1966 mlb draft he was 22 years old when he reached the majors in 1970 with the yankees spending four and a half years with them before moving to the cleveland indians 1974 and atlanta braves 1977 in his rookie season for the yankees he went 66 with a 341 era in 15 starts and won 12 games a year later including careernumbers with 81 strikeouts and 15 complete gameshis most productive season came in 1972 when he recorded careerhighs in wins 16 era 240 starts 32 shutouts 4 and innings pitched 236 he declined after that and was sent to cleveland in a major early season 1974 trade that sent chris chambliss and dick tidrow to the bronx kline missed the 1975 season with arm problems and spent 1976 back in minor league baseball before making 16 relief appearances for atlanta in 1977 his last major league seasonin a sixseason mlb career kline posted a 4345 record with 240 strikeouts and a 326 era in 750 innings and 129 games pitched 105 as a starter he allowed 708 hits and 184 bases on ballshe now is a pitching coach at wenatchee high school 4a in wa